# Generated by Django 4.1.3 on 2022-12-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checho', '0002_remove_citas_fecha_citas_dia_alter_citas_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='estado',
            field=models.IntegerField(default='0'),
        ),
    ]
