# Generated by Django 4.0.6 on 2022-12-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checho', '0003_disponibilidad_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='semana',
            field=models.IntegerField(default='0'),
        ),
    ]
